name: Tests
on:
  pull_request:
    branches:
      - '**.x'
  push:
    branches:
      - '**.x'
      - release-*
jobs:
  testing:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Lint syntax / code convention
        run: composer lint

      - name: Run unit tests
        run: composer test
